-- Clean existing data
TRUNCATE TABLE "Booking" CASCADE;
TRUNCATE TABLE "Theater" CASCADE;
TRUNCATE TABLE "users" CASCADE;

-- Seed data for theaters
INSERT INTO "Theater" (
    "id",
    "name",
    "location",
    "city",
    "country",
    "address",
    "facilities",
    "capacity",
    "showTimes",
    "regularPriceWeekday",
    "regularPriceWeekend",
    "vipPriceWeekday",
    "vipPriceWeekend",
    "createdAt",
    "updatedAt"
) VALUES 
(
    '1',
    'CGV Grand Indonesia',
    'Grand Indonesia Mall',
    'Jakarta',
    'Indonesia',
    'Jl. M.H. Thamrin No.1, Kebon Melati, Jakarta Pusat',
    ARRAY['IMAX', 'Dolby Atmos', 'VIP Lounge', 'Parking'],
    300,
    ARRAY['10:00', '13:00', '16:00', '19:00', '22:00'],
    8,
    12,
    15,
    20,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    '2',
    'XXI Plaza Indonesia',
    'Plaza Indonesia',
    'Jakarta',
    'Indonesia',
    'Jl. M.H. Thamrin Kav. 28-30, Gondangdia, Jakarta Pusat',
    ARRAY['4DX', 'Dolby Surround', 'Cafe'],
    250,
    ARRAY['11:00', '14:00', '17:00', '20:00'],
    7,
    10,
    13,
    18,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    '3',
    'AMC Empire 25',
    'Times Square',
    'New York',
    'United States',
    '234 W 42nd St, New York, NY 10036',
    ARRAY['IMAX', 'Dolby Cinema', 'RealD 3D', 'Recliners'],
    400,
    ARRAY['11:00', '14:30', '18:00', '21:30', '23:59'],
    16,
    20,
    25,
    30,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    '4',
    'TCL Chinese Theatre',
    'Hollywood Boulevard',
    'Los Angeles',
    'United States',
    '6925 Hollywood Blvd, Hollywood, CA 90028',
    ARRAY['IMAX Laser', 'VIP Experience', 'Historic Venue'],
    932,
    ARRAY['10:00', '13:30', '17:00', '20:30', '23:00'],
    18,
    22,
    28,
    35,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    '5',
    'Odeon Luxe Leicester Square',
    'Leicester Square',
    'London',
    'United Kingdom',
    '24-26 Leicester Square, London WC2H 7JY',
    ARRAY['IMAX', 'Dolby Cinema', 'Luxury Recliners', 'Royal Box'],
    800,
    ARRAY['12:00', '15:30', '19:00', '22:30'],
    15,
    19,
    25,
    32,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    '6',
    'TOHO Cinemas Shinjuku',
    'Shinjuku',
    'Tokyo',
    'Japan',
    '1 Chome-19-1 Kabukicho, Shinjuku City, Tokyo 160-0021',
    ARRAY['IMAX', 'MX4D', 'Premium Seats', 'Couples Seats'],
    350,
    ARRAY['09:00', '12:30', '16:00', '19:30', '23:00'],
    12,
    15,
    20,
    25,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    '7',
    'CGV Yongsan I''Park Mall',
    'Yongsan I''Park Mall',
    'Seoul',
    'South Korea',
    '55 Hangang-daero 23-gil, Yongsan-gu, Seoul',
    ARRAY['4DX', 'SCREENX', 'Gold Class', 'Sweet Box'],
    450,
    ARRAY['10:30', '14:00', '17:30', '21:00', '23:30'],
    11,
    14,
    18,
    23,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    '8',
    'Event Cinemas George Street',
    'George Street',
    'Sydney',
    'Australia',
    '505-525 George St, Sydney NSW 2000',
    ARRAY['VMAX', 'Gold Class', '4DX', 'Dolby Atmos'],
    500,
    ARRAY['10:00', '13:30', '17:00', '20:30', '23:00'],
    14,
    18,
    22,
    28,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    '9',
    'Shaw Theatres Lido IMAX',
    'Shaw House',
    'Singapore',
    'Singapore',
    '350 Orchard Road, Shaw House Level 5 & 6',
    ARRAY['IMAX', 'Lumiere', 'Dreamers', 'Premium Seats'],
    350,
    ARRAY['11:30', '15:00', '18:30', '22:00'],
    13,
    16,
    20,
    25,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    '10',
    'Reel Cinemas The Dubai Mall',
    'The Dubai Mall',
    'Dubai',
    'United Arab Emirates',
    'The Dubai Mall, Financial Center Road',
    ARRAY['Platinum Suites', 'Dine-in Cinema', 'MX4D', 'IMAX'],
    600,
    ARRAY['12:00', '15:30', '19:00', '22:30', '01:00'],
    15,
    20,
    35,
    45,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
); 